name: 배포

on:
  workflow_dispatch:
    inputs:
      image:
        description: '배포할 이미지 선택'
        required: true
        type: choice
        options:
          - recipick-backend-admin
          - recipick-backend-user
          - recipick-backend-crawler

jobs:
  deploy:
    name: ${{ github.event.inputs.image }} → ${{ github.ref_name }} 배포
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.image }}:${{ github.ref_name == 'main' && 'prod' || github.ref_name == 'dev' && 'dev' || 'invalid' }}

    steps:
      - name: 브랜치 검증
        run: |
          if [ "${{ github.ref_name }}" != "main" ] && [ "${{ github.ref_name }}" != "dev" ]; then
            echo "❌ 배포는 main 또는 dev 브랜치에서만 가능합니다. 현재 브랜치: ${{ github.ref_name }}"
            exit 1
          fi
          echo "✅ 브랜치 검증 완료: ${{ github.ref_name }}"

      - name: 환경 변수 설정
        id: env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "environment=prod" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

      - name: 서버 정보 설정
        id: server
        run: |
          if [ "${{ steps.env.outputs.environment }}" = "prod" ]; then
            echo "host=${{ secrets.PROD_SERVER_HOST }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.PROD_SERVER_USER }}" >> $GITHUB_OUTPUT
            {
              echo 'key<<EOF'
              echo '${{ secrets.PROD_SERVER_SSH_KEY }}'
              echo 'EOF'
            } >> $GITHUB_OUTPUT
            echo "port=${{ secrets.PROD_SERVER_PORT }}" >> $GITHUB_OUTPUT
          else
            echo "host=${{ secrets.DEV_SERVER_HOST }}" >> $GITHUB_OUTPUT
            echo "user=${{ secrets.DEV_SERVER_USER }}" >> $GITHUB_OUTPUT
            {
              echo 'key<<EOF'
              echo '${{ secrets.DEV_SERVER_SSH_KEY }}'
              echo 'EOF'
            } >> $GITHUB_OUTPUT
            echo "port=${{ secrets.DEV_SERVER_PORT }}" >> $GITHUB_OUTPUT
          fi

      - name: SSH 배포 실행
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ steps.server.outputs.host }}
          username: ${{ steps.server.outputs.user }}
          key: ${{ steps.server.outputs.key }}
          port: ${{ steps.server.outputs.port }}
          script: |
            set -e

            IMAGE="ghcr.io/${{ github.repository_owner }}/${{ github.event.inputs.image }}:${{ steps.env.outputs.environment }}"
            CONTAINER="${{ github.event.inputs.image }}"

            docker stop $CONTAINER 2>/dev/null || true
            docker rm $CONTAINER 2>/dev/null || true
            docker pull $IMAGE
            docker image prune -f || true

            case "${{ github.event.inputs.image }}:${{ steps.env.outputs.environment }}" in
              "recipick-backend-admin:dev")
                docker run -d \
                  --name $CONTAINER \
                  --restart unless-stopped \
                  --network recipick \
                  -p 8091:8080 \
                  $IMAGE
                ;;
              "recipick-backend-admin:prod")
                docker run -d \
                  --name $CONTAINER \
                  --restart unless-stopped \
                  --network recipick \
                  -p 8081:8080 \
                  $IMAGE
                ;;
              "recipick-backend-user:dev")
                docker run -d \
                  --name $CONTAINER \
                  --restart unless-stopped \
                  --network recipick \
                  -p 8092:8080 \
                  $IMAGE
                ;;
              "recipick-backend-user:prod")
                docker run -d \
                  --name $CONTAINER \
                  --restart unless-stopped \
                  --network recipick \
                  -p 8082:8080 \
                  $IMAGE
                ;;
              "recipick-backend-crawler:dev")
                docker run -d \
                  --name $CONTAINER \
                  --restart unless-stopped \
                  --network recipick \
                  $IMAGE
                ;;
              "recipick-backend-crawler:prod")
                docker run -d \
                  --name $CONTAINER \
                  --restart unless-stopped \
                  --network recipick \
                  $IMAGE
                ;;
              *)
                exit 1
                ;;
            esac

            sleep 5
            docker ps --filter "name=$CONTAINER" || exit 1