name: Recipick Backend Product CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changes.outputs.changes }}
      root-changed: ${{ steps.changes.outputs.root }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          list-files: json
          filters: |
            admin-api: 'apps/admin-api/**'
            admin-auth: 'apps/admin-auth/**'
            user-api: 'apps/user-api/**'
            user-auth: 'apps/user-auth/**'
            batch: 'apps/batch/**'
            crawler: 'apps/crawler/**'
            root:
              - '!apps/**'
              - '!libs/**'
              - '**'

  build:
    needs: detect-changes
    if: needs.detect-changes.outputs.matrix != '[]' || needs.detect-changes.outputs.root-changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-changes.outputs.root-changed == 'true' && '["admin-api", "admin-auth", "user-api", "user-auth", "batch", "crawler"]' || needs.detect-changes.outputs.matrix) }}
    environment: ${{ matrix.module }}-prod
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: MODULE=${{ matrix.module }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/recipick-backend-${{ matrix.module }}:prod
            ${{ secrets.DOCKERHUB_USERNAME }}/recipick-backend-${{ matrix.module }}:prod-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: [detect-changes, build]
    if: needs.detect-changes.outputs.matrix != '[]' || needs.detect-changes.outputs.root-changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-changes.outputs.root-changed == 'true' && '["admin-api", "admin-auth", "user-api", "user-auth", "batch", "crawler"]' || needs.detect-changes.outputs.matrix) }}
    environment: ${{ matrix.module }}-prod
    steps:
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop recipick-backend-${{ matrix.module }} || true
            docker rm recipick-backend-${{ matrix.module }} || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/recipick-backend-${{ matrix.module }}:prod
            docker run -d \
              --name recipick-backend-${{ matrix.module }} \
              -p ${{ vars.APP_PORT }}:8080 \
              --restart unless-stopped \
              ${{ secrets.DOCKERHUB_USERNAME }}/recipick-backend-${{ matrix.module }}:prod